<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>bankruptcy</name>
  <uuid>1f2a8023-e22a-4f29-a0ed-623b12a70e52</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'the bankruptcy check' is true
then
    set decision to a new Rejection where rejected is 
     true, the reason is  "History of Bankruptcy" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
