<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>1fd0496d-fd1c-4a7c-8f2e-ab1d651a97d5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Rejection where rejected is  false ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
