<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>b62b8b6d-46e2-4b4c-a14a-3012e7912c90</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to an empty list of Loan Packages ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
