<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule-1</name>
  <uuid>f6b97c06-0cac-4152-a7ca-aaa286196721</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision  to 'the loan packages based on histories' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
