<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Turnover rules</name>
  <uuid>a5ee5060-7f7b-482d-8add-9eb21cb2c4f5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'the SMB loan packages' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
