<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check potential discount</name>
  <uuid>f297d2e8-d101-4590-bb2c-3dc6f13ca1bb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
    the number_of_employees of 'the business' is between 2 and 20 and
    the turnover of 'the business' is less than 5000000  
then
    for each Loan Package in decision :
        - set the rate_of_interest of this Loan Package to the rate_of_interest of this Loan Package - 0.25 , ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
