<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>50e86761-c7f4-4d6b-b1d6-0ad13832e8ae</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to an empty list of Loan Packages ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
