<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule-1</name>
  <uuid>908190b1-4ab4-48e9-972a-66375d6e0d14</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 'the turnover loan packages' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
